[package]
name = "viterbi"
lang = "c++11"

[lib]
lang = "c++98"

[[bin]]
path = "tests/viterbi_main.cpp"

[[test]]
path = "tests/viterbi_test.cpp"

[dev-dependencies]
gtest = { git = "https://github.com/google/googletest.git" }

[options.gtest]
BUILD_GMOCK = false
